version: '3.4'

networks:
  backend:

services:
  notebookdb:
   container_name: notebook-db
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Password@123#
   networks:
     - backend
   ports:
     - 8001:1433
  notebookapi:
    container_name: notebook-api
    image: ${DOCKER_REGISTRY-}notebookapi
    build:
      context: .
      dockerfile: NotebookApi/Dockerfile
    networks:
       - backend
    ports:
       - 5000:5000
    environment:
        - DB_HOST=notebookdb
        - DB_NAME=notebook-db
        - DB_SA_PASSWORD=Password@123#

  messagedb:
    container_name: message-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password@123#
      - POSTGRES_DB=message-db
    networks:
      - backend
    ports:
      - 5432:5432
    restart: always
    volumes:
      - message_data:/var/lib/postgresql/data/ 
  messageapi:
    container_name: message-api
    image: ${DOCKER_REGISTRY-}messageapi
    build:
      context: .
      dockerfile: MessageApi/Dockerfile
    networks:
      - backend
    ports:
      - 5001:5001
    environment:
      - ConnectionString=host=host.docker.internal;port=5432;database=message-db;username=postgres;password=Password@123#;Pooling=true;

volumes:
 message_data:
  
